import Foundation

/// Ce qu'on a lu sur le presse-papiers, sans encore savoir si on le garde.
/// Fichier PUR : aucun AppKit, donc toute la politique se teste sans presse-papiers.
struct RawSnapshot {
    let types: [String]
    let text: String?
    let rtf: Data?
    let image: Data?
    let fileURLs: [String]
    let sourceBundleID: String?
    /// La vignette PNG de l'image, fabriquée par le presse-papiers système et
    /// simplement transportée jusqu'à la base. `var` avec une valeur par défaut, et
    /// non `let` : c'est ce qui laisse les vingt et un `RawSnapshot(...)` déjà écrits
    /// dans les tests compiler sans être touchés.
    var vignette: Data?
}

enum CaptureDecision: Equatable {
    case ignore(String)
    case keep(ClipKind)
}

/// Les règles d'exclusion. C'est l'objection numéro un du corpus : la question du
/// mot de passe copié est posée trois fois indépendamment dans le seul fil Maccy.
struct CapturePolicy {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    var blockedBundleIDs: Set<String> = []
    /// Optionnelle et désactivée par défaut : elle sert au cas des secrets copiés
    /// depuis un terminal, qui n'exposent aucun marqueur de confidentialité. Les
    /// applications qui en posent un (`org.nspasteboard.ConcealedType`, par exemple un
    /// gestionnaire de mots de passe) sont déjà ignorées sans ce motif.
    var secretPattern: String?

    func decide(_ s: RawSnapshot) -> CaptureDecision {
        if s.types.contains(Self.concealed) {
            return .ignore("confidentiel")
        }
        if s.types.contains(Self.transient) {
            return .ignore("transitoire")
        }
        if s.types.contains(Self.autoGenerated) {
            return .ignore("auto-généré")
        }
        if let id = s.sourceBundleID, blockedBundleIDs.contains(id) {
            return .ignore("app exclue")
        }

        if let motif = secretPattern, let texte = s.text,
           texte.range(of: motif, options: .regularExpression) != nil
        {
            return .ignore("motif secret")
        }

        // La représentation la plus riche gagne, dans cet ordre.
        if !s.fileURLs.isEmpty {
            return .keep(.files)
        }
        if s.image != nil {
            return .keep(.image)
        }
        if s.rtf != nil {
            return .keep(.rtf)
        }
        if let t = s.text, !t.isEmpty {
            return .keep(.text)
        }
        return .ignore("vide")
    }
}
